name: CI

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Setup PHP
        uses: shivammathur/setup-php@c1fd36d4f0c5d0f4ebd74a1d6540c3f4bf4f3306
        with:
          php-version: '8.3'
      - name: Lint
        run: php -l hello.php
      - name: Run
        run: php hello.php
